#!/bin/sh

PKGNAME=$(sed -n "s/Package: *\([^ ]*\)/\1/p" DESCRIPTION)
PKGVERS=$(sed -n "s/Version: *\([^ ]*\)/\1/p" DESCRIPTION)
PKGSRC=$(pwd)
PKGDIR=$(Rscript -e "cat(.libPaths()[1])")

echo $PKGNAME
echo $PKGVERS
echo $PKGSRC
echo $PKGDIR

cd $PKGDIR/$PKGNAME/node/nodered_custom
npm install
cd $PKGDIR/$PKGNAME/node/nodered_custom/rflow-rstudio-nodes
npm link
cd $PKGDIR/$PKGNAME/node/nodered_custom
npm link rflow-rstudio-nodes